### ISSUE TITLE
Add new Documentation section?

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/series#16]
We're experimenting with a [6-lesson series](https://openscapes.github.io/2023-epa/) in which Call 2 introduces Pathways in more depth, and adds a new section on Documentation. Maybe Corey and Anna have some documentation on Documentation that we could add.

**Comment by jules32** [comment]
Great idea; we can add it to the additional lessons section (we can add an index.md at the same time!)

e.g. https://openscapes.github.io/series/additional-lessons/code-of-conduct.html

**Comment by stefaniebutland** [comment]
See PR https://github.com/Openscapes/series/pull/18
