### ISSUE TITLE
Update NSSD Spreadsheet Drama link

### ISSUE THREAD

**Issue by jules32** [Openscapes/series#22]
Check Not So Standard Deviations Spreadsheet Drama link (with Jenny Bryan). If broken, update to: 

Update to https://simplystatistics.org/posts/2016-02-12-not-so-standard-deviations-episode-9-spreadsheet-drama/

This shows up in: 
- Data strategies chapter
- Data strategies slides

**Comment by stefaniebutland** [comment]
Link works in slides.  
I don't see mention of it in Series Data strategies chapter but we can add it

**Comment by jules32** [comment]
Great link works in slides; we can close
