### ISSUE TITLE
Series: lightly update Open Communities - Oct 3 for Oct 10 Call 4

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/series#28]
lightly update Open Communities narrative, screenshots in Series.
will do this the week before Oct 10 Fred Hutch Call 04.

**Comment by stefaniebutland** [comment]
[PR](https://github.com/Openscapes/series/pull/38) ready for @jules32 review

**Comment by jules32** [comment]
Closing, thanks Stef!
