### ISSUE TITLE
Move & link to efficiency tips folder - Sep 29

### ISSUE THREAD

**Issue by jules32** [Openscapes/series#32]
## Status 

The example agendas linked from https://openscapes.github.io/series/#cohort-agendas are out-of-date. Since agendas with kyber are pretty stable, let's use Fred Hutch as a chance to update this folder. 

## Plan

1) @stefaniebutland , when you create blank agendas for Fred Hutch, will you please also create copies in [this public folder](https://drive.google.com/drive/folders/1Iq8tj81TSfr-RstphVTZWoz783xpJMOb?usp=sharing)

2) Review other files and see if still relevant/helpful and if there are updates needed, and add to the public folder above. This screenshot is from the current link 

<img width="389" alt="image" src="https://github.com/Openscapes/series/assets/5891909/ac8eeab2-482d-4429-9cbd-9ae5d8a74395">

**Comment by jules32** [comment]
Note: this will happen after I've completed the main rework for the Mindset section; I'll re-assign Stef at that point.

**Comment by jules32** [comment]
An update for @stefaniebutland - 

I've removed the "Cohort Agendas" section - here is a screenshot of how it used to look: 

~~

<img width="954" alt="image" src="https://github.com/Openscapes/series/assets/5891909/007626a2-4ffe-48d1-bcbc-bae42362a3f1">
~~

So in the Series, you'll only need to please uncomment this line when the new agendas are available: 

```
<!--- (Template agendas, as well as slides, tips, and other resources we use are openly available in this [Google Folder](https://drive.google.com/open?id=1HQHXlMVgg9lp2IYkzj8LSAG5bjyKFS6g), ready for reuse and remix).

TODO: https://github.com/Openscapes/series/issues/32
--->
```

**Comment by jules32** [comment]
@stefaniebutland thanks for getting the public folder started; could you please add the efficiency tips file as a new file in the public folder? Thank you!

- [ ] add efficiency tips @stefaniebutland 
- [ ] add text and link from Series book @jules32

**Comment by stefaniebutland** [comment]
@jules32 new file called `OpenscapesEffiencyTips`.
I added our current tips at the top, then added content from the original file below those. Didn't test or edit those (yet?)

**Comment by jules32** [comment]
Thanks for moving Stef, this is good for now! I'll close :)
