### ISSUE TITLE
Link to Slides folder in Series

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/series#39]
@jules32  Can I add a shortcut to the [OpenscapesChampionsSlides](https://drive.google.com/drive/folders/1XBWck1UQ0-XXe2aN-H4pXiaQsImZUl0Z?usp=drive_link) folder to our public Google Folder to complete this:

Series: [Welcome - Cohort Calls](https://openscapes.github.io/series/#cohort-calls)
> Template agendas, as well as **slides**, tips, and other resources we use are openly available in this [Google Folder](https://drive.google.com/drive/folders/1Iq8tj81TSfr-RstphVTZWoz783xpJMOb), ready for reuse and remix.

how-to: Do I create shortcut then move it to the public folder?
![Screenshot 2023-10-16 at 10 43 43 AM](https://github.com/Openscapes/series/assets/11927811/1c67f2fd-1858-4953-8e4b-e4bf801758ab)

**Comment by jules32** [comment]
yes, a shortcut sounds good; if you think better you could also move the ChampionsSlides to the public folder.

**Comment by stefaniebutland** [comment]
✅ move the ChampionsSlides to the public folder.

![Screenshot 2023-10-16 at 11 13 26 AM](https://github.com/Openscapes/series/assets/11927811/23fb38f3-6e18-48a7-ba98-c53d29af4739)
