### ISSUE TITLE
Fix broken link to https://eco-data-science.github.io/

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/series#47]
at https://openscapes.github.io/series/core-lessons/#deliverables

used as example of a coding club.

**Comment by stefaniebutland** [comment]
may be resolved by https://github.com/Openscapes/series/issues/48 Update Deliverables text on Core Lessons page

**Comment by jules32** [comment]
Addressed in https://github.com/Openscapes/series/pull/53
