### ISSUE TITLE
Update Deliverables text on Core Lessons page

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/series#48]
## [Deliverables](https://openscapes.github.io/series/core-lessons/#deliverables)

Revisit Deliverables heading and content in light of current approach

- [x] delete [What would you do in a Study Group?](https://openscapes.github.io/series/core-lessons/#what-would-you-do-in-a-study-group)
  - links under heading are old or broken; best to delete this section and focus on Seaside Chats + Coworking between Cohort Calls
- [x] replace Assignments with Coworking description?
- [x] Revisit Additional reading on Core Lessons page -> good links but better elsewhere? Here share the links we send in Welcome email to a cohort

broken link issue https://github.com/Openscapes/series/issues/47 may be resolved by this issue

**Comment by jules32** [comment]
Thanks for starting this issue Stef; I completed all tasks, and moved Additional Reading to Inspiration section (for now)

**Comment by jules32** [comment]
Started https://github.com/Openscapes/series/pull/53
