### ISSUE TITLE
Checking links throughout Series

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/series#50]
Confirmed all links work on the following pages

- [x] Welcome
- [x] Core Lessons index.qmd
  - [x] Mindset
  - [x] Better science
  - [x] GitHub strategies
  - [x] Team Culture
  - [x] Data Strategies
  - [x] Coding strategies
  - [x] Open Communities
  - [x] Pathways
- [x] Additional Lessons
  - [x] Code of Conduct
  - [x] RMarkdown for scicomm -> propose deprecating this in #51 
  - [x] Documentation
- [x] Community Lessons
- [x] How do I index.qmd
  - [x] Discuss Community
- [x] Inspriration

**Comment by jules32** [comment]
Thanks Stef for starting this list and your start to the review!

My progress to date in this PR: https://github.com/Openscapes/series/pull/53, checking off the list as I go!

**Comment by jules32** [comment]
OK I have completed reviewing all links and updating those chapters! Thank you for making this list!
