### ISSUE TITLE
Rename or deprecate Community Lessons page?

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/series#52]
It seems like [Community Lessons](https://openscapes.github.io/series/community-lessons/) content can already be found in other lessons pages (as the Series has evolved).

Is this a place to rename and point to things like [Openscapes at the Water Boards](https://cawaterboarddatacenter.github.io/swrcb-openscapes/), NASA Openscapes, NMFS Openscapes? Or do we deprecate Community Lessons page and ensure the content is represented elsewhere?

The name Community Lessons conflicts with "Open Communities"; not clear to reader how they will differ.

**Comment by jules32** [comment]
I think we'll rename - it's showcasing what Openscapes Champions have done to build communities within their orgs/teams. How to rename?

(not great/bad) starting ideas:

1. "Openscapes in the wild"
2. "Champions extending Openscapes"
3. "'Forking' Openscapes in other orgs"
4. "Openscapes Flywheel turning at other orgs"

**Comment by stefaniebutland** [comment]
I like Openscapes in the wild. Gives leeway for what we can include. 
Openscapes Flywheel turning at other orgs can stump folks if they don't get the Flywheel

**Comment by jules32** [comment]
As I worked on this, I thought that "Forked Lessons" was the best rename - it includes the word "Lessons" for consistency on the navbar, and the concept of "Forking" is something that has resonated with other groups outside of coding (for example, at the NIH NLM equity in open science workshop). I have made these changes in https://github.com/Openscapes/series/pull/53!
